version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      # Login to ECR
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Configuring the EKS Cluster authentication...
      - aws configure set region $AWS_DEFAULT_REGION
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $KUBE_SECRET_NAME --query 'SecretString' --output text)
      - echo "$SECRET_JSON" > kubeconfig.yaml
      - chmod 644 kubeconfig.yaml
      - export KUBECONFIG=$CODEBUILD_SRC_DIR/kubeconfig.yaml
      - aws eks --region us-east-1 update-kubeconfig --name comm-cluster
      # Generate Docker Images Tags
      - RANDOM=$(openssl rand -base64 10 | tr -dc '0-9')
      - GRPC_IMAGE_TAG=$(echo "grpc-$RANDOM")
      - WEB_IMAGE_TAG=$(echo "web-$RANDOM")

  build:
    commands:
      - echo Build started on `date`
      - echo Building the grpcserver Docker image...
      - docker build app/grpcserver/. -t $GRPC_IMAGE_TAG
      - docker tag $GRPC_IMAGE_TAG:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$GRPC_IMAGE_TAG     
      - echo Building the webserver Docker image...
      - docker build app/webserver/. -t $WEB_IMAGE_TAG
      - docker tag $WEB_IMAGE_TAG:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$WEB_IMAGE_TAG     
      - echo Build completed on `date`
      - docker images

  post_build:
    commands:
      - echo "Pushing the grpc-server Docker image to ECR Repo $IMAGE_REPO_NAME"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$GRPC_IMAGE_TAG
      - echo "Pushing the  web-server Docker image to ECR Repo $IMAGE_REPO_NAME"
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$WEB_IMAGE_TAG 
      - Applying Kubernetes manifests...           
      - cd kubernetes
      - sed -i "s|\grpc-imagetag|$GRPC_IMAGE_TAG|g" grpcserver-deployment.yml
      - sed -i "s|\web-imagetag|$WEB_IMAGE_TAG|g" webserver-deployment.yml 
      - kubectl apply -f .
      - echo Post_Build completed on `date`