apiVersion: apps/v1												
kind: Deployment										
metadata:												
  name: grpcserver-deployment	
  labels:												
    app: grpcserver						
    type: back-end
spec:													
  template:
    metadata:												
      name: grpcserver-pod						
      labels:												
        app: grpcserver						
        type: back-end						
    spec:													
      containers:											
        - name: grpcserver-container						
          image: GRPC-TAG-PLACEHOLDER
          ports:
            - containerPort: 50051
          resources:
            limits:
              cpu: 250m
              memory: 128Mi          
  replicas: 1
  selector:
    matchLabels:
      app: grpcserver
      type: back-end