apiVersion: apps/v1												
kind: Deployment										
metadata:												
  name: webserver-deployment	
  labels:												
    app: webserver						
    type: front-end
spec:													
  template:
    metadata:												
      name: webserver-pod						
      labels:												
        app: webserver						
        type: front-end						
    spec:													
      containers:											
        - name: webserver-container						
          image: WEB-TAG-PLACEHOLDER
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 250m
              memory: 128Mi   
  replicas: 1
  selector:
    matchLabels:
      app: webserver
      type: front-end