# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comm.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\x12\x0c\x63omunicacion\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2[\n\rCommunication\x12J\n\x0bSendMessage\x12\x1c.comunicacion.MessageRequest\x1a\x1d.comunicacion.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEREQUEST']._serialized_start=28
  _globals['_MESSAGEREQUEST']._serialized_end=61
  _globals['_MESSAGERESPONSE']._serialized_start=63
  _globals['_MESSAGERESPONSE']._serialized_end=97
  _globals['_COMMUNICATION']._serialized_start=99
  _globals['_COMMUNICATION']._serialized_end=190
# @@protoc_insertion_point(module_scope)
